---
# flag to enable/disable the debug generation
debug: false
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### kmeans class debug params #####
kmeans:
    debugAlgorithm: false
    debugMetric: false
    centerTitles: false
    dataTitles: false
    identityTitle: false
    displayFactor: 0.2
    display: centroid # centroid or center

##### descriptor calculation params #####
descriptor:
    type: SHOT # DCH, SHOT, USC, PFH, ROPS

    patchSize: 0.03 # mts
    bandNumber: 8
    bandWidth: 0.005 # mts
    bidirectional: false
    useProjection: false
    sequenceBin: 0.01 # mts
    sequenceStat: mean # mean or median

    DCH:
      searchRadius: 0.03 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      binNumber: 3
      sequenceStat: mean # mean, median, hist
    SHOT:
      searchRadius: 0.02 # mts
    USC:
      searchRadius: 0.02 # mts
    PFH:
      searchRadius: 0.02 # mts
    ROPS:
      searchRadius: 0.02 # mts

##### clustering params #####
clustering:
    implementation: opencv # opencv, kmeans, stochastic
    metric: [closest, conf] # metric and args (euclidean, closest or closest_with_confidence)
    clusterNumber: 50
    maxIterations: 200
    stopThreshold: 0.0001
    attempts: 3
    generateElbowCurve: false
    generateDistanceMatrix: false

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005
...