---
# flag to enable/disable the debug generation
debug: false

##### kmeans class debug params #####
kmeans:
    debugAlgorith: false
    debugMetric: false
    centerTitles: false
    dataTitles: false
    identityTitle: false
    displayFactor: 0.2
    display: centroid # centroid or center

    ##### clustering params #####
clustering:
    implementation: kmeans # opencv, kmeans or stochastic
    metric: [closest, 4] # metric and args (euclidean, closest or closest_with_confidence)
    clusterNumber: 7
    maxIterations: 300
    stopThreshold: 0.0001
    attempts: 3
    generateElbowCurve: false
    generateDistanceMatrix: false
...