---
# flag to enable/disable the debug generation
debug: false

##### clustering params #####
clustering:
    implementation: custom # opencv, custom or stochastic
    metric: [closest, 4] # metric and args (euclidean, closest or closest_with_confidence)
    clusterNumber: 7
    maxIterations: 300
    stopThreshold: 0.0001
    attempts: 3
    generateElbowCurve: false
    generateDistanceMatrix: false
...