---
# flag to enable/disable the debug generation
debug: false
# cloud's descriptor target 
targetPoint: 4108 #2238 sphere 9586
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### descriptor calculation params #####
descriptor:
    type: DCH
    DCH:
      searchRadius: 0.02 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      binNumber: 3 # 3 bins of 0.01 mts
      stat: mean # mean, median, hist10, hist20, hb20, hb10

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005

##### Synthetic cloud generation params #####
syntheticCloud:
    generateCloud: false
    type: plane # cube, cylinder, sphere, half_sphere, plane
...