---
# flag to enable/disable the debug generation
debug: false
idDebug: true
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### descriptor calculation params #####
descriptor:
    type: DCH # DCH, SHOT, USC, PFH, ROPS
    DCH:
      searchRadius: 0.03 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      sequenceBin: 0.01 # mts
      sequenceStat: histogram # mean, median, histogram
    SHOT:
      searchRadius: 0.03 # mts
    USC:
      searchRadius: 0.02 # mts
    PFH:
      searchRadius: 0.02 # mts
    ROPS:
      searchRadius: 0.02 # mts
...