---
# flag to enable/disable the debug generation
debug: false
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/
# location of the codebook used for the labeling
codebookLocation: config/bow50_c7_1E-4_kmeans.dat

##### labeling params #####
labeling:
    type: svm # metric or svm
    args: [closest, conf] # arguments according to the labeling type

##### descriptor calculation params #####
descriptor:
    type: DCH
    DCH:
      searchRadius: 0.02 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      binNumber: 4 # 4 bins of 0.005 mts
      stat: mean # mean, median, hist10, hist20, hb20, hb10
    SHOT:
      searchRadius: 0.02 # mts
    USC:
      searchRadius: 0.02 # mts
    PFH:
      searchRadius: 0.02 # mts
    ROPS:
      searchRadius: 0.03 # mts
      partitionsNumber: 5
      rotationsNumber: 3
      supportRadius: 0.025
    SpinImage:
      searchRadius: 0.03 # mts
      imageWidth: 8

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005
...