---
# flag to enable/disable the debug generation
debug: false
# cloud's descriptor target 
targetPoint: 2238
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### descriptor calculation params #####
descriptor:
    searchRadius: 0.03 # mts
    bandNumber: 8
    bandWidth: 0.005 # mts
    bidirectional: false
    useProjection: false
    sequenceBin: 0.01 # mts
    sequenceStat: mean # mean or median

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005

##### Synthetic cloud generation params #####
syntheticCloud:
    generateCloud: false
    type: half_sphere # cube, cylinder, sphere, half_sphere, plane
...