---
# flag to enable/disable the debug generation
debug: false
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### kmeans class debug params #####
kmeans:
    debugAlgorithm: false
    debugMetric: false
    centerTitles: false
    dataTitles: false
    identityTitle: false
    displayFactor: 0.2
    display: centroid # centroid or center

##### descriptor calculation params #####
descriptor:
    type: DCH # DCH, SHOT, USC, PFH, FPFH, ROPS, SpinImage
    DCH:
      searchRadius: 0.03 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      binNumber: 3
      stat: hist10 # mean, median, hist10, hist20, hb20, hb10
    SHOT:
      searchRadius: 0.035 # mts
    USC:
      searchRadius: 0.035 # mts
    PFH:
      searchRadius: 0.035 # mts
    FPFH:
      searchRadius: 0.035 # mts
    ROPS:
      searchRadius: 0.035 # mts
      partitionsNumber: 5
      rotationsNumber: 3
      supportRadius: 0.025
    SpinImage:
      searchRadius: 0.035 # mts
      imageWidth: 8

##### clustering params #####
clustering:
    implementation: opencv # opencv, kmeans, stochastic
    metric: [closest, conf] # metric and args (euclidean, closest or closest_with_confidence)
    clusterNumber: 200
    maxIterations: 500
    stopThreshold: 0.0001
    attempts: 3
    generateElbowCurve: false
    generateDistanceMatrix: false

##### cloud smoothing params #####
cloudSmoothing:
    useSmoothing: true
    sigma: 4
    radius: 0.005
...