---
# flag to enable/disable the debug generation
debug: false
idDebug: false
# radius used for the normal vectors estimation
normalEstimationRadius: -1
# calculation cache directory
cacheLocation: ../cache/

##### descriptor calculation params #####
descriptor:
    type: DCH # DCH, SHOT, USC, PFH, FPFH, ROPS, SpinImage
    DCH:
      searchRadius: 0.03 # mts
      bandNumber: 8
      bandWidth: 0.005 # mts
      bidirectional: false
      useProjection: false
      binNumber: 3 # 3 bins of 0.01 mts
      stat: 'hist20' # mean, median, hist10, hist20, hb20, hb10
    SHOT:
      searchRadius: 0.035 # mts
    USC:
      searchRadius: 0.035 # mts
    PFH:
      searchRadius: 0.035 # mts
    FPFH:
      searchRadius: 0.035 # mts
    ROPS:
      searchRadius: 0.035 # mts
      partitionsNumber: 5
      rotationsNumber: 3
      supportRadius: 0.025
    SpinImage:
      searchRadius: 0.035 # mts
      imageWidth: 8
...